"use client";
import { ThemeProvider } from "@mui/material";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import localFont from "next/font/local";
import store from "./store";
import theme from "./providers/Theme";

const robotoFont = localFont({
  src: [
    {
      path: "../../public/fonts/roboto/Roboto-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/roboto/Roboto-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/roboto/Roboto-Italic.ttf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-roboto",
  display: "swap",
});

const roobert = localFont({
  src: [
    {
      path: "../../public/fonts/roobertMono/RoobertSemiMonoTRIAL-Medium.otf",
      weight: "600",
      style: "medium",
    },
    {
      path: "../../public/fonts/roobertMono/RoobertSemiMono-heavy.otf",
      weight: "800",
      style: "bold",
    },
    {
      path: "../../public/fonts/roobertMono/RoobertSemiMonoTRIAL-SemiBold-BF67243fd539b9e.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/roobertMono/RoobertTRIAL-Regular.otf",
      weight: "500",
      style: "regular",
    },
  ],
  variable: "--font-roobert",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible+Next:ital,wght@0,200..800;1,200..800&family=Montserrat:ital@0;1&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoFont.variable} ${roobert.variable} antialiased`}
      >
        <ThemeProvider theme={theme}>
          <Provider store={store}>{children}</Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
